name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - 3.x
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BINARY_PATH: brut.apktool/apktool-lib/src/main/resources/prebuilt

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    name: Build apktool.jar
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4.4.1
        with:
          dependency-graph: generate-and-submit

      - name: Build (Linux/Mac)
        run: ./gradlew build shadowJar proguard

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: brut.apktool/apktool-cli/build/libs/*
